### ISSUE TITLE
Game hangs when Election failed 3 times and election tracker hit the end

### ISSUE THREAD

**Issue by LDcuth** [ShrimpCryptid/Secret-Hitler-Online#12] opened 2021-07-10 01:35 UTC
When failing 3 elections, the game will pass the top policy instead. But instead, the game hangs. User can be back and join the lobby to play the same game again.

Video capture:
https://user-images.githubusercontent.com/48134214/125148018-34ec5180-e0e4-11eb-8e0d-2f0bce54eebc.mp4

**Comment by ShrimpCryptid** [comment] 2021-07-10 04:49
Thanks for the video, this is super helpful. I'm sitting down to look at a couple bugs including this one tonight.

**Comment by ShrimpCryptid** [comment] 2021-07-10 04:51
https://github.com/ShrimpCryptid/Secret-Hitler-Online/issues/11#issuecomment-873612150

May be the same issue as described in this comment.

**Comment by Hacime** [comment] 2021-07-29 18:32
I have tried different websites to play secret hitler online and this is my favorite one. Well done.
Unfortunately, we also get this bug and have to login again into the game to continue playing, as shown in the video.

Additionally, we always get a fascist policy, even it shows liberal during the animation, on the board appears a fascist policy.
I wanted to inform about this also.
Would be really cool, if this could be fixed, as this project is so well done.

**Comment by ShrimpCryptid** [comment] 2021-07-31 18:10
I really appreciate the kind words! I'm currently very busy but I have some time today to look at the project. I'll report back if I find anything.

**Comment by ShrimpCryptid** [comment] 2021-07-31 19:49
Okay, I think I figured out this issue!

It was occurring when two alert animations were queued up one after the other. What should have been happening was that, when the alert was closed, the alert box content should be blanked (reset), the alert should be closed, and the next animation should be cued up (which in this case sets a new alert box content).
The bug was caused by these steps being out of order. The new alert box content was being set by the next animation, but the current animation immediately blanked it. 

This issue is fixed in the latest build of the website.

@Hacime I wasn't able to recreate the second issue you described. If you're still encountering it after the latest build, please open a new issue!

**Closed by ShrimpCryptid** 2021-07-31 19:49 UTC
